accounts/urls.py
from django.urls import path
from accounts.views import *

app_name = 'accounts'
urlpatterns = [
    # path('register/', RegisterView.as_view(), name='register'),
    path('login/', login_view, name='login'),
    path('verify-otp/', VerifyOtpView.as_view(), name='verify-otp'),
    path('logout/', logout_view, name='logout'),
    path('login/submit/', login_submit, name='login_submit'),
    path('create/creator/', CreateUserView.as_view(), name="create_creator"),
    path('create/admin/', CreateAdminView.as_view(), name="create_admin"),
    path('admins/', AdminListView.as_view(), name="admin_list"),
    path('creator/<int:pk>/delete/', DeleteUserView.as_view(), name="delete_creator"),
    path('user/<int:pk>/update/', UpdateUserPassword.as_view(), name="update_user_password"),
    path('admins/<int:pk>/update/', AdminUpdateView.as_view(), name="admin_update"),
    path('', dashboard, name='dashboard'),
    path('calender/', calender_view, name='calendar'),
    path('directorySearch/', directorySearch, name='directorySearch'),
    path('profile/own/', own_profile_details,name='own_profile_details'),
    path('password-change/own/', own_password_change,name='own_password_change'),

]

jitsi_helper/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from qr_code import urls as qr_code_urls

urlpatterns = [
    # path('admin/', admin.site.urls),
    url(r'^qr_code/', include(qr_code_urls, namespace="qr_code")),
    url(r'^', include('accounts.urls')),
    url(r'^', include('room.urls')),
    url(r'^', include('restrictions.urls')),
]

restrictions/urls.py
from django.urls import path
from .views import *

app_name = 'restrictions'
urlpatterns = [
    path('restriction/', RestrictionListView.as_view(), name='restriction_list'),
    path('restriction/update/<int:pk>/', RestrictionUpdateView.as_view(), name='restriction_update'),
]

room/urls.py
from django.urls import path
from room.views import *

app_name = 'room'
urlpatterns = [
    path('room/create/', RoomCreateView.as_view(), name='create_room'),
    path('room/', RoomListView.as_view(), name='room_list'),
    path('room/<int:pk>/join/', RoomJoinView.as_view(), name='join_room'),
    path('room/<int:pk>/delete/', RoomDeleteView.as_view(), name='delete_room'),
    path('room/<str:uid>/join/as-guest/', GuestJoinView.as_view(), name='join_guest_room'),
    path('room/update/<int:pk>/', RoomUpdateView.as_view(), name='room_update'),
    path('room/<int:pk>/details/json/', RoomJsonDetailsView.as_view(), name="room_json_details"),
    path('room/sync_google/json/', RoomSyncGoogle.as_view(), name="room_google_sync"),
    path('room/sync_outlook/json/', RoomSyncOutlook.as_view(), name="room_outlook_sync"),
    path('room/google_calender/not_synced/json/', RoomGoogleCalenderListView.as_view(), name="room_google_calender"),
    path('room/outlook_calender/not_synced/json/', RoomOutlookCalenderListView.as_view(), name="room_outlook_calender"),
]

restrictions/models.py
from django.db import models
from accounts.models import JitsiUser
from django.utils.translation import ugettext_lazy as _

# Create your models here.
from room.models import Room


class Restrictions(models.Model):
	user = models.OneToOneField(JitsiUser, models.CASCADE, related_name='restrictions', unique=True)
	max_room_count = models.IntegerField(_("Maximum room a user can create"), default=0)
	max_time_length = models.IntegerField(_("Maximum time length of a room(in minute)"), default=0)
	max_member_count = models.IntegerField(_("Maximum number of guest in a room"), default=0)

	@staticmethod
	def can_create_new_room(user):
		restriction = Restrictions.objects.filter(user=user).first()
		if restriction:
			if restriction.max_room_count < 0:
				return True
			rooms_by_user = Room.objects.filter(created_by=user)
			if rooms_by_user.count() >= restriction.max_room_count:
				return False
		return True

restrictions/forms.py
from django import forms

from restrictions.models import Restrictions


class RestrictionForm(forms.ModelForm):
    class Meta:
        model = Restrictions
        fields = ['user', 'max_member_count', 'max_room_count', 'max_time_length']
        help_texts = {
            "max_time_length": "Please put -1 if you want unlimited",
            "max_room_count": "Please put -1 if you want unlimited",
            "max_member_count": "Please put -1 if you want unlimited",
        }
        widgets = {
            'user': forms.HiddenInput(),
            'max_time_length': forms.NumberInput(attrs={"class": "form-control"}),
            "max_room_count": forms.NumberInput(attrs={"class": "form-control"}),
            'max_member_count': forms.NumberInput(attrs={"class": "form-control"})
        }


class RestrictionFormWithoutUserForm(forms.ModelForm):
    class Meta:
        model = Restrictions
        fields = ['max_member_count', 'max_room_count', 'max_time_length']
        help_texts = {
            "max_time_length": "Please put -1 if you want unlimited",
            "max_room_count": "Please put -1 if you want unlimited",
            "max_member_count": "Please put -1 if you want unlimited",
        }
        widgets = {
            'max_time_length': forms.NumberInput(attrs={"class": "form-control"}),
            "max_room_count": forms.NumberInput(attrs={"class": "form-control"}),
            'max_member_count': forms.NumberInput(attrs={"class": "form-control"})
        }

restrictions/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import ListView, UpdateView

from restrictions.forms import RestrictionForm
from restrictions.models import Restrictions


@method_decorator(login_required, name="dispatch")
class RestrictionListView(ListView):
    model = Restrictions
    template_name = 'restrictions/list.html'

    def get_queryset(self):
        return self.model.objects.filter(user__is_staff=False, user__is_superuser=False)

@method_decorator(login_required, name="dispatch")
class RestrictionUpdateView(UpdateView):
    model = Restrictions
    form_class = RestrictionForm
    template_name = 'restrictions/update.html'

    def get_object(self, queryset=None):
        return self.model.objects.get(pk=self.kwargs.get('pk'))

    def get_success_url(self):
        return '/restriction/'

restrictions/templates/restrictions/list.html
{% extends 'base.html' %}
{% block contents %}
    <div>
    <h3 class="pull-left">Manage Host Users</h3>

    <div class="clearfix"></div>
    </div>
    <table class="table">
        <tr>
            <th>User Name</th>
            <th>Maximum meetings count</th>
            <th>Maximum time length of meeting</th>
            <th>Maximum number of guest</th>
            <th></th>
        </tr>
        {% for restriction in object_list %}
            <tr>
                <td>{{ restriction.user }}</td>
                <td>
                    {% if restriction.max_room_count < 0 %}
                    Unlimited
                    {% else %}
                    {{ restriction.max_room_count }}
                    {% endif %}
                </td>
                <td>
                    {% if restriction.max_time_length < 0 %}
                    Unlimited
                    {% else %}
                    {{ restriction.max_time_length }}
                    {% endif %}
                </td>
                <td>
                    {% if restriction.max_member_count < 0 %}
                    Unlimited
                    {% else %}
                    {{ restriction.max_member_count }}
                    {% endif %}
                </td>

                <td>
                    <a href="{% url 'restrictions:restriction_update' restriction.id %}" class="btn btn-primary">Update</a>
                    {% if user.is_staff and user.is_superuser %}
                    <a href="{% url 'accounts:update_user_password' restriction.user.id %}" class="btn btn-primary">Update Password</a>
                    {% endif %}
                    <a href="{% url 'accounts:delete_creator' restriction.user.id %}" class="btn btn-danger">Delete user</a>
                </td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

restrictions/templates/restrictions/update.html
{% extends 'base.html' %}
{% block contents %}
    <h4>Update Host User</h4>
    <hr/>
    {% if form.errors %}
        <div class="alert alert-danger">
            {{ form.errors }}
        </div>
    {% endif %}
    <form action="." method="post">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                {% if field.field.widget.is_hidden is not True %}
                    {% if field.field.required %}
                        <label>{{ field.label }}<span class="required"> * </span></label>
                    {% else %}
                        <label>{{ field.label }}</label>
                    {% endif %}
                {% endif %}
                {{ field }}
                {% if field.help_text %}
                <small class="form-text text-muted">{{ field.help_text }}</small>
                {% endif %}
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-large btn-primary">Update</button>
    </form>
{% endblock %}