jitsi_helper/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from qr_code import urls as qr_code_urls

urlpatterns = [
    # path('admin/', admin.site.urls),
    url(r'^qr_code/', include(qr_code_urls, namespace="qr_code")),
    url(r'^', include('accounts.urls')),
    url(r'^', include('room.urls')),
    url(r'^', include('restrictions.urls')),
]

room/urls.py
from django.urls import path
from room.views import *

app_name = 'room'
urlpatterns = [
    path('room/create/', RoomCreateView.as_view(), name='create_room'),
    path('room/', RoomListView.as_view(), name='room_list'),
    path('room/<int:pk>/join/', RoomJoinView.as_view(), name='join_room'),
    path('room/<int:pk>/delete/', RoomDeleteView.as_view(), name='delete_room'),
    path('room/<str:uid>/join/as-guest/', GuestJoinView.as_view(), name='join_guest_room'),
    path('room/update/<int:pk>/', RoomUpdateView.as_view(), name='room_update'),
    path('room/<int:pk>/details/json/', RoomJsonDetailsView.as_view(), name="room_json_details"),
    path('room/sync_google/json/', RoomSyncGoogle.as_view(), name="room_google_sync"),
    path('room/sync_outlook/json/', RoomSyncOutlook.as_view(), name="room_outlook_sync"),
    path('room/google_calender/not_synced/json/', RoomGoogleCalenderListView.as_view(), name="room_google_calender"),
    path('room/outlook_calender/not_synced/json/', RoomOutlookCalenderListView.as_view(), name="room_outlook_calender"),
]

room/models.py
from time import time

from django.db import models

# Create your models here.
from accounts.models import JitsiUser
from django.utils.translation import ugettext_lazy as _


class Room(models.Model):
    PUBLIC, PRIVATE = "public", "private"
    ROOM_TYPE = ((PUBLIC, "Public"), (PRIVATE, "Private"),)

    name = models.CharField(max_length=255)
    room_id = models.CharField(max_length=255)
    room_type = models.CharField(max_length=255, choices=ROOM_TYPE, default='public')
    created_by = models.ForeignKey(JitsiUser, on_delete=models.CASCADE, related_name='created_rooms')
    is_active = models.BooleanField(default=True)
    max_number_of_user = models.IntegerField(_("Maximum number of users"), default=-1)
    start_time = models.BigIntegerField(default=0)
    host_join_time = models.BigIntegerField(null=True)
    end_time = models.BigIntegerField(default=0)
    max_length = models.IntegerField(_("Maximum meeting time length (in Minutes)"), default=-1)
    password = models.CharField(max_length=20, null=True)
    is_google_synced = models.BooleanField(default=False)
    is_outlook_synced = models.BooleanField(default=False)

    def status(self):
        time_now = int(time())*1000
        if self.start_time > time_now:
            return "Not started yet"
        if self.start_time < time_now and self.max_length > 0:
            if time_now > (self.start_time+self.max_length*60*1000):
                return "Ended"
        return "On going"

room/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

from accounts.models import JitsiUser
from restrictions.models import Restrictions
from room.models import Room
from django.utils.translation import ugettext_lazy as _

class RoomPasswordForm(forms.Form):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    guest_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))

    def __init__(self, room, *args, **kwargs):
        super(RoomPasswordForm, self).__init__(*args, **kwargs)
        self.room = room
        if not self.room.password:
            self.fields['password'].required = False
            self.fields['password'].widget = forms.HiddenInput()

    def clean(self):
        super().clean()
        password = self.data.get('password')
        if self.room.password is not None and self.room.password != password:
            self.add_error('password',
                           'please give a valid password')


class RoomForm(forms.ModelForm):

    def __init__(self, user, *args, **kwargs):
        super(RoomForm, self).__init__(*args, **kwargs)
        self.user = user
        self.fields['password'].required = False

    def clean(self):
        super().clean()
        restriction = Restrictions.objects.filter(user=self.user).first()
        if not self.user.is_staff and not self.user.is_superuser and restriction:
            max_number_of_user = int(self.data.get('max_number_of_user'))
            max_length = int(self.data.get('max_length'))

            if restriction.max_member_count > 0 and (max_number_of_user > restriction.max_member_count or max_number_of_user < 0):
                self.add_error('max_number_of_user','You cannot set Maximum number of guest in a meeting more than {value}'.format(value=restriction.max_member_count))
            if restriction.max_time_length > 0 and (max_length > restriction.max_time_length or max_length < 0):
                self.add_error('max_length','You cannot set time length of a meeting more than {value}'.format(value=restriction.max_time_length))

    class Meta:
        model = Room
        fields = ['name', 'password', 'max_number_of_user', 'max_length', 'start_time']
        help_texts = {
            "max_number_of_user": "Please put -1 if you want unlimited",
            "max_length": "Please put -1 if you want unlimited",
        }

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'password': forms.TextInput(attrs={'class': 'form-control'}),
            'max_number_of_user': forms.TextInput(attrs={'class': 'form-control'}),
            'max_length': forms.TextInput(attrs={'class': 'form-control'}),
            'start_time': forms.HiddenInput()
        }

room/views.py
import secrets
import uuid
from datetime import datetime
from time import time
from uuid import UUID

import jwt
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404

# Create your views here.
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import ListView

from accounts.models import UserProfile
from jitsi_helper.local import SITE_URL, VIDEO_URL, GOOGLE_API_KEY, MICROSOFT_CLIENT_ID, GOOGLE_CLIENT_ID
from jitsi_helper.settings import JITSI_AUD, JITSI_ISSUER, JITSI_PRIVATE_KEY, JITSI_URL
from restrictions.models import Restrictions
from room.forms import RoomForm, RoomPasswordForm
from room.models import Room


@method_decorator(login_required, name="dispatch")
class RoomCreateView(View):
    template_name = 'room/room_create.html'
    form = RoomForm

    def get(self, request):

        if not request.user.is_staff and not request.user.is_superuser and not Restrictions.can_create_new_room(request.user) :
            max_room_count = Restrictions.objects.get(user=request.user).max_room_count
            messages.add_message(request, messages.ERROR, 'You cannot create more than {} meetings.'.format(max_room_count))
            return redirect(reverse('room:room_list'))
        form = self.form(request.user)
        return render(request, self.template_name, locals())

    def post(self, request):
        form = self.form(data=request.POST, user=request.user)
        if form.is_valid():
            room = form.save(commit=False)
            room.room_id = str(int(time())*1000)
            room.created_by = request.user
            if room.max_length > 0:
                room.end_time = room.start_time + room.max_length*60*1000
            room.save()
            form.save_m2m()
            return redirect(reverse('room:room_list'))
        return render(request, self.template_name, locals())


@method_decorator(login_required, name="dispatch")
class RoomUpdateView(View):
    form = RoomForm
    template_name = 'room/room_create.html'

    def get(self, request, *args, **kwargs):
        room_obj = get_object_or_404(Room, pk=kwargs.get('pk'), created_by=request.user)
        form = self.form(instance=room_obj, user=self.request.user)
        update=True
        return render(request, self.template_name, locals())

    def post(self, request, *args, **kwargs):
        room_obj = get_object_or_404(Room, pk=kwargs.get('pk'), created_by=request.user)
        form = self.form(data=request.POST, instance=room_obj, user=self.request.user)
        update=True
        if form.is_valid():
            room = form.save(commit=False)
            if room.max_length > 0:
                room.end_time = room.start_time + room.max_length*60*1000
            room.save()

            form.save_m2m()
            return redirect(reverse('room:room_list'))
        return render(request, self.template_name, locals())


@method_decorator(login_required, name="dispatch")
class RoomListView(ListView):
    model = Room

    def get_queryset(self):
        now_time = int(time())*1000
        return Room.objects.filter(
            created_by=self.request.user
        )

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(RoomListView, self).get_context_data(**kwargs)
        context['googleApiKey'] = GOOGLE_API_KEY
        context['googleClientId'] = GOOGLE_CLIENT_ID
        context['msClientId'] = MICROSOFT_CLIENT_ID
        context['site_url'] = SITE_URL
        return context


@method_decorator(login_required, name="dispatch")
class RoomJsonDetailsView(View):
    def get(self, request, *args, **kwargs):
        room_id = kwargs.get('pk')
        room = Room.objects.get(pk = room_id)
        room_dict = {
            "id": room.id,
            "start_time": room.start_time,
            "max_length": room.max_length,
            "host_join_time": room.host_join_time
        }
        return JsonResponse(data=room_dict)


@method_decorator(login_required, name="dispatch")
class RoomSyncGoogle(View):
    def get(self, request):
        room_id = request.GET.get('room_id')
        room = Room.objects.get(id=room_id)
        is_synced = int(request.GET.get('is_synced', '0'))
        is_synced = bool(is_synced)
        room.is_google_synced = is_synced
        room.save()
        return JsonResponse(data={"success": True})


@method_decorator(login_required, name="dispatch")
class RoomSyncOutlook(View):
    def get(self, request):
        room_id = request.GET.get('room_id')
        room = Room.objects.get(id=room_id)
        is_synced = int(request.GET.get('is_synced', '0'))
        is_synced = bool(is_synced)
        room.is_outlook_synced = is_synced
        room.save()
        return JsonResponse(data={"success": True})

@method_decorator(login_required, name="dispatch")
class RoomGoogleCalenderListView(View):
    def get(self, request):
        rooms = Room.objects.filter(created_by=self.request.user, is_active=True, room_type=Room.PUBLIC, is_google_synced=False).filter(Q(max_length=-1) | Q(start_time__gte=int(time()*1000))).all()
        result = []
        for room in rooms:
            result.append({
                "id": room.id,
                "room_id": room.room_id,

                "name": room.name,
                "already_started": True if room.start_time <= int(time()*1000) else False,
                "start_time": room.start_time,
                "max_length": room.max_length,
                "host_join_time": room.host_join_time
            })
        return JsonResponse(data=result, safe=False)

@method_decorator(login_required, name="dispatch")
class RoomOutlookCalenderListView(View):
    def get(self, request):
        rooms = Room.objects.filter(created_by=self.request.user, is_active=True, room_type=Room.PUBLIC, is_outlook_synced=False).filter(Q(max_length=-1) | Q(start_time__gte=int(time()*1000))).all()
        result = []
        for room in rooms:
            result.append({
                "id": room.id,
                "room_id": room.room_id,

                "name": room.name,
                "already_started": True if room.start_time <= int(time()*1000) else False,
                "start_time": room.start_time,
                "max_length": room.max_length,
                "host_join_time": room.host_join_time
            })
        return JsonResponse(data=result, safe=False)

@method_decorator(login_required, name="dispatch")
class RoomJoinView(View):
    template = 'room/join.html'

    def get(self, request, *args, **kwargs):
        room_obj = get_object_or_404(Room, pk=kwargs.get('pk'))
        is_active = True
        has_access = False
        if not room_obj.is_active:
            is_active = False
        if room_obj.room_type == Room.PUBLIC:
            has_access = True
        elif room_obj.created_by == request.user:
            has_access = True

        if room_obj.created_by == request.user:
            if not room_obj.host_join_time:
                room_obj.host_join_time = int(time())*1000
                room_obj.save()
            is_moderator = True
        if is_active and has_access:
            headers = {
            }
            payload = {
                "context": {
                    "user": {
                        "avatar": "https:/gravatar.com/avatar/abc123",
                        "name": "{} {}".format(request.user.first_name, request.user.last_name),
                        "email": request.user.email,
                        "id": request.user.profile.user_uid,
                        "p_id": str(request.user.id),
                        "room_id": str(room_obj.id)
                    },
                    "room_info": {
                        "id": str(room_obj.id),
                        "name": room_obj.name,
                        "creator": room_obj.created_by.profile.user_uid,
                        "room_type": room_obj.room_type,
                        "moderator": room_obj.created_by.profile.user_uid
                    },
                    "group": "a123-123-456-789"
                },
                "aud": JITSI_AUD,
                "iss": JITSI_ISSUER,
                "sub": "example_app_id",
                "room": room_obj.room_id,
                "exp": 1685141372
            }
            domain = VIDEO_URL
            creator = room_obj.created_by.profile.user_uid
            token = jwt.encode(payload, "example_app_secret", algorithm='HS256', headers=headers).decode('utf-8')
            return render(request, self.template, locals())


@method_decorator(login_required, name="dispatch")
class RoomDeleteView(View):
    def get(self, request, *args, **kwargs):
        room_id = kwargs.get('pk')
        room = Room.objects.get(created_by=request.user, id=room_id)
        room.delete()
        return redirect(reverse('room:room_list'))

class GuestJoinView(View):
    template = "room/join_guest.html"
    password_template = 'room/password_prompt.html'
    password_form = RoomPasswordForm

    def get(self, request, *args, **kwargs):
        room_obj = get_object_or_404(Room, room_id=kwargs.get('uid'))
        form = self.password_form(room=room_obj)
        return render(request, self.password_template, locals())

    def post(self, request, *args, **kwargs):
        room_obj = get_object_or_404(Room, room_id=kwargs.get('uid'))
        form = self.password_form(room=room_obj, data=request.POST)
        if form.is_valid():
            guest_name = form.cleaned_data.get('guest_name')
            return self.join_room(request, room_obj, guest_name)
        return render(request, self.password_template, locals())

    def join_room(self, request, room_obj, guest_name):
        is_active = True
        has_access = False

room/templates/room/join.html
{% extends 'layout.html' %}
{% load staticfiles %}
{% block title %}VoipX meet{% endblock %}
{% block contents %}
        {% if not is_active %}
            <h3 class="text-center">Sorry this room is not active</h3>
        {% elif not has_access %}
            <h3 class="text-center">You have no permission in this room</h3>
        {% endif %}

        {% if is_active and has_access %}

            <div class="row">
                <div class="col-md-12">
                    {% if room_obj.start_time and room_obj.max_length > 0 %}
                        <h1>Time remaining: <span id="remaining_time_span"></span></h1>
                    {% endif %}
                    <div id="meet"></div>
                </div>

            </div>
        {% endif %}
{% endblock %}
{% block page_scripts %}
    <script src='{% static 'js/external_api.min.js' %}'></script>
    <script type="text/javascript">

        $(function () {
            const domain = '{{ domain }}';
            const options = {
                roomName: '{{ room_obj.room_id }}',
                width: '100%',
                height: 700,
                parentNode: document.querySelector('#meet'),
                jwt: '{{ token }}'

            };
            const api = new JitsiMeetExternalAPI(domain, options);
            var isModeratorHere = false;
            {% if is_moderator %}
                isModeratorHere = true;
            {% endif %}
            api.executeCommand('displayName', '{{ user.profile.name }}');

            api.executeCommand('subject', '{{ room_obj.name }}');

            api.addEventListener('videoConferenceLeft', function () {
                window.location = "{% url 'room:room_list' %}";
            });

            {% if room_obj.password %}
                api.executeCommand('password', '{{ room_obj.password }}');
            {% endif %}

            api.addEventListener('participantJoined', function (data) {
                {% if not room_obj.host_join_time and room_obj.max_length > 0 %}
                    if(!isModeratorHere) {
                        $.ajax({
                            url: '{% url 'room:room_json_details' room_obj.id %}'
                        }).done(function (data) {
                            if(data['host_join_time'] && data['max_length']) {
                                console.log("Moderator joined");
                                isModeratorHere = true;
                                startCountDown(parseInt(data['host_join_time']), parseInt(data['max_length']) )
                            }
                        });
                    }
                {% endif %}
            });

            {% if room_obj.host_join_time and room_obj.max_length > 0  %}
                startCountDown({{ room_obj.host_join_time }}, {{ room_obj.max_length }});
            {% endif %}

            function startCountDown(start_time, max_length) {
                var end_time = start_time + max_length * 60 * 1000;
                setInterval(function () {
                    if(end_time-moment().valueOf()>0) {
                        var remaining_time = moment.duration(end_time - moment().valueOf(), 'milliseconds');
                        var remaining_time_text = remaining_time.minutes() + " minutes " + remaining_time.seconds() + " seconds";
                        if(remaining_time.hours() > 0) {
                            remaining_time_text = remaining_time.hours() + " hours "+remaining_time_text;
                        }
                        $("#remaining_time_span").text(remaining_time_text);
                    }
                    else{
                        $("#remaining_time_span").text("Finished");
                        window.location = "{% url 'room:room_list' %}";
                    }
                }, 1000);
            }
        });
    </script>
{% endblock %}

room/templates/room/join_guest.html
{% extends 'layout.html' %}
{% load staticfiles %}
{% block title %}VoipX meet{% endblock %}
{% block contents %}
        {% if not is_active %}
            <h3 class="text-center">Sorry this room is not active</h3>
        {% elif not has_access %}
            <h3 class="text-center">You have no permission in this room</h3>
        {% endif %}

        {% if is_active and has_access %}

            <div class="row">
                <div class="col-md-12">
                    {% if room_obj.start_time and room_obj.max_length > 0 %}
                        <h1>Time remaining: <span id="remaining_time_span"></span></h1>
                    {% endif %}
                    <div id="meet"></div>
                </div>

            </div>
        {% endif %}
{% endblock %}
{% block page_scripts %}
    <script src='{% static 'js/external_api.min.js' %}'></script>
    <script type="text/javascript">

        $(function () {
            const domain = '{{ domain }}';
            const options = {
                roomName: '{{ room_obj.room_id }}',
                width: '100%',
                height: 700,
                parentNode: document.querySelector('#meet'),
                jwt: '{{ token }}',
                interfaceConfigOverwrite: {
                    TOOLBAR_BUTTONS: [
                        'microphone', 'camera', 'desktop', 'fullscreen',
                        'fodeviceselection', 'hangup', 'profile', 'chat',
                         'etherpad', 'settings', 'raisehand',
                        'videoquality', 'filmstrip',   'shortcuts',
                        'tileview',  'mute-everyone',
                        'e2ee'
                    ],
                    SHOW_BRAND_WATERMARK: true,
                    BRAND_WATERMARK_LINK: 'https://talk.gomeeting.org:8000{% static 'img/company_logo.jpeg' %}',
                }

            };
            const api = new JitsiMeetExternalAPI(domain, options);
            var isModeratorHere = false;
            {% if is_moderator %}
                isModeratorHere = true;
            {% endif %}

            api.executeCommand('subject', '{{ room_obj.name }}');

            api.addEventListener('videoConferenceLeft', function () {
                window.location = "https://www.voipxpbx.com/";
             });

            api.addEventListener('participantJoined', function (data) {
                {% if not room_obj.host_join_time and room_obj.max_length > 0 %}
                    if(!isModeratorHere) {
                        $.ajax({
                            url: '{% url 'room:room_json_details' room_obj.id %}'
                        }).done(function (data) {
                            if(data['host_join_time'] && data['max_length']) {
                                console.log("Moderator joined");
                                isModeratorHere = true;
                                startCountDown(parseInt(data['host_join_time']), parseInt(data['max_length']) )
                            }
                        });
                    }
                {% endif %}
            });

            {% if room_obj.host_join_time and room_obj.max_length > 0  %}
                startCountDown({{ room_obj.host_join_time }}, {{ room_obj.max_length }});
            {% endif %}

            function startCountDown(start_time, max_length) {
                var end_time = start_time + max_length * 60 * 1000;
                setInterval(function () {
                    if(end_time-moment().valueOf()>0) {
                        var remaining_time = moment.duration(end_time - moment().valueOf(), 'milliseconds');
                        var remaining_time_text = remaining_time.minutes() + " minutes " + remaining_time.seconds() + " seconds";
                        if(remaining_time.hours() > 0) {
                            remaining_time_text = remaining_time.hours() + " hours "+remaining_time_text;
                        }
                        $("#remaining_time_span").text(remaining_time_text);
                    }
                    else{
                        $("#remaining_time_span").text("Finished");

                    }
                }, 1000);
            }
        });
    </script>
{% endblock %}

room/templates/room/password_prompt.html
{% extends "layout.html" %}
{% load staticfiles %}

{% block contents %}
    <div class="container">
        <div class="text-center p20">
            <img src="{% static 'img/company_logo.jpeg' %}" width="250">
        </div>
        <div class="text-center p20">
            <h1>Welcome</h1>
        </div>
        {% if errors %}
            <div class="alert alert-danger margin-center" style="width: 400px;">{{ errors }}</div>
        {% endif %}
        <div class="card shadow panel p30 margin-center" style="width: 400px;">
            {% if form.errors %}
                <div class="alert alert-danger">
                    {{ form.errors }}
                </div>
            {% endif %}
            <form action="." method="post">
                {% csrf_token %}
                {% for field in form.visible_fields %}
                    <div class="form-group">
                        {% if field.field.widget.is_hidden is not True %}
                            {% if field.field.required %}
                                <label>{{ field.label }}<span class="required"> * </span></label>
                            {% else %}
                                <label>{{ field.label }}</label>
                            {% endif %}
                        {% endif %}
                        {{ field }}
                    </div>
                {% endfor %}

                {% for field in profile_form.visible_fields %}
                    <div class="form-group">
                        {% if field.field.widget.is_hidden is not True %}
                            {% if field.field.required %}
                                <label>{{ field.label }}<span class="required"> * </span></label>
                            {% else %}
                                <label>{{ field.label }}</label>
                            {% endif %}
                        {% endif %}
                        {{ field }}
                    </div>
                {% endfor %}

                <div class="clearfix">
                    <div class="pull-right">
                        <button type="submit" class="btn btn-default">Go to room</button>
                    </div>
                </div>
            </form>
        </div>

    </div>
{% endblock %}
{% block page_scripts %}
    <script type="text/javascript">
        $(function () {
            {% if not room_obj.password %}
            $("#id_password").hide();
            {% endif %}
        });
    </script>
{% endblock %}

room/templates/room/room_create.html
{% extends 'base.html' %}
{% block contents %}
    <h4>
        {% if update %}
        Update meeting
        {% else %}
        Create a new meeting
        {% endif %}
    </h4>
    <hr/>
    {% if form.errors %}
        <div class="alert alert-danger">
            {{ form.errors }}
        </div>
    {% endif %}

    <form action="." method="post">
        {% csrf_token %}
        {{ form.start_time }}
        {% for field in form.visible_fields %}
            <div class="form-group">
                {% if field.field.widget.is_hidden is not True %}
                    {% if field.field.required %}
                        <label>{{ field.label }}<span class="required"> * </span></label>
                    {% else %}
                        <label>{{ field.label }}</label>
                    {% endif %}
                {% endif %}
                {{ field }}
                {% if field.help_text %}
                <small class="form-text text-muted">{{ field.help_text }}</small>
                {% endif %}

            </div>
        {% endfor %}
        <div class="form-group">
            <label>Start Time<span class="required"> * </span></label>
            <div class='input-group date' id='datetimepicker1'>
                <input type='text' class="form-control" />
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
            </div>
        </div>
        <button type="submit" class="btn btn-large btn-primary">
            {% if update %}
            Update
            {% else %}
            Create
            {% endif %}
        </button>
    </form>

{% endblock %}

{% block page_script %}
    <script type="text/javascript">
        $(function () {
            var start_time = moment();
            var form_start_time = parseInt($("#id_start_time").val());
            if (form_start_time != 0 ) {
                start_time = moment(form_start_time);
            }
            else {
                $("#id_start_time").val(start_time.valueOf());
            }
            $('#datetimepicker1').datetimepicker({
                format: 'DD/MM/YYYY hh:mm a',
                defaultDate: start_time
            });
            $('#datetimepicker1').on('dp.change', function(e){
                console.log(e.date);
                $("#id_start_time").val(e.date.valueOf());
            });
        });

    </script>
{% endblock %}