accounts/urls.py
from django.urls import path
from accounts.views import *

app_name = 'accounts'
urlpatterns = [
    # path('register/', RegisterView.as_view(), name='register'),
    path('login/', login_view, name='login'),
    path('verify-otp/', VerifyOtpView.as_view(), name='verify-otp'),
    path('logout/', logout_view, name='logout'),
    path('login/submit/', login_submit, name='login_submit'),
    path('create/creator/', CreateUserView.as_view(), name="create_creator"),
    path('create/admin/', CreateAdminView.as_view(), name="create_admin"),
    path('admins/', AdminListView.as_view(), name="admin_list"),
    path('creator/<int:pk>/delete/', DeleteUserView.as_view(), name="delete_creator"),
    path('user/<int:pk>/update/', UpdateUserPassword.as_view(), name="update_user_password"),
    path('admins/<int:pk>/update/', AdminUpdateView.as_view(), name="admin_update"),
    path('', dashboard, name='dashboard'),
    path('calender/', calender_view, name='calendar'),
    path('directorySearch/', directorySearch, name='directorySearch'),
    path('profile/own/', own_profile_details,name='own_profile_details'),
    path('password-change/own/', own_password_change,name='own_password_change'),

]

jitsi_helper/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from qr_code import urls as qr_code_urls

urlpatterns = [
    # path('admin/', admin.site.urls),
    url(r'^qr_code/', include(qr_code_urls, namespace="qr_code")),
    url(r'^', include('accounts.urls')),
    url(r'^', include('room.urls')),
    url(r'^', include('restrictions.urls')),
]

restrictions/urls.py
from django.urls import path
from .views import *

app_name = 'restrictions'
urlpatterns = [
    path('restriction/', RestrictionListView.as_view(), name='restriction_list'),
    path('restriction/update/<int:pk>/', RestrictionUpdateView.as_view(), name='restriction_update'),
]

room/urls.py
from django.urls import path
from room.views import *

app_name = 'room'
urlpatterns = [
    path('room/create/', RoomCreateView.as_view(), name='create_room'),
    path('room/', RoomListView.as_view(), name='room_list'),
    path('room/<int:pk>/join/', RoomJoinView.as_view(), name='join_room'),
    path('room/<int:pk>/delete/', RoomDeleteView.as_view(), name='delete_room'),
    path('room/<str:uid>/join/as-guest/', GuestJoinView.as_view(), name='join_guest_room'),
    path('room/update/<int:pk>/', RoomUpdateView.as_view(), name='room_update'),
    path('room/<int:pk>/details/json/', RoomJsonDetailsView.as_view(), name="room_json_details"),
    path('room/sync_google/json/', RoomSyncGoogle.as_view(), name="room_google_sync"),
    path('room/sync_outlook/json/', RoomSyncOutlook.as_view(), name="room_outlook_sync"),
    path('room/google_calender/not_synced/json/', RoomGoogleCalenderListView.as_view(), name="room_google_calender"),
    path('room/outlook_calender/not_synced/json/', RoomOutlookCalenderListView.as_view(), name="room_outlook_calender"),
]

templates/includes/css.html
{% load staticfiles %}
{% load compress %}
<link href="https://fonts.googleapis.com/css?family=Encode+Sans&display=swap" rel="stylesheet">
{% compress css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
    <link href="{% static 'css/select2.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'css/bootstrap-datepicker.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/justifiedGallery.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/colorbox-master/colorbox.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/rateyo/jquery.rateyo.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-datetimepicker.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/priyo.css' %}?v=114">
{% endcompress %}

templates/includes/js.html
{% load staticfiles %}

<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'js/jquery-ui.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.1/js/select2.min.js"></script>
<script src="{% static 'js/cookie.js' %}"></script>
<script src="{% static 'js/alert.js' %}"></script>
<script src="{% static 'js/jquery.blockUI.js' %}"></script>
<script src="{% static 'js/sweetalert.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.bundle.min.js" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/js/bootstrap-datepicker.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.20.1/moment.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>

<script src="{% static 'js/jquery.justifiedGallery.min.js' %}"></script>
<script src="{% static 'js/imagesloaded.pkgd.min.js' %}"></script>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<script src="{% static 'js/script.js' %}?v=164"></script>
<script>
    $("#menu-toggle").click(function (e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });

    var MONTHS = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
		var config = {
			type: 'line',
			data: {
				labels: ["January", "February", "March", "April", "May", "June", "July"],
				datasets: [{
					label: "My First dataset",
					borderColor: 'rgb(255, 99, 132)',
					backgroundColor: 'rgb(255, 99, 132)',
					data: [
                        9,
                        190,
                        30,
                        2,
                        79,
                        40,
                        30
                    ]
				}, {
					label: "My Second dataset",
					borderColor: 'rgb(54, 162, 235)',
					backgroundColor: 'rgb(54, 162, 235)',
					data: [
                        9,
                        190,
                        30,
                        2,
                        79,
                        40,
                        30
                    ],
				}, {
					label: "My Third dataset",
					borderColor: 'rgb(75, 192, 192)',
					backgroundColor: 'rgb(75, 192, 192)',
					data: [
                        9,
                        190,
                        30,
                        2,
                        79,
                        40,
                        30
                    ],
				}, {
					label: "My Third dataset",
					borderColor: 'rgb(255, 205, 86)',
					backgroundColor: 'rgb(255, 205, 86)',
					data: [
                        9,
                        190,
                        30,
                        2,
                        79,
                        40,
                        30
                    ],
				}]
			},
			options: {
				responsive: true,
				tooltips: {
					mode: 'index',
				},
				hover: {
					mode: 'index'
				},
				scales: {
					xAxes: [{
						scaleLabel: {
							display: true,
							labelString: 'Month'
						}
					}],
					yAxes: [{
						stacked: true,
						scaleLabel: {
							display: true,
							labelString: 'Value'
						}
					}]
				}
			}
		};

		window.onload = function() {
			//var ctx = document.getElementById("canvas").getContext("2d");
			//window.myLine = new Chart(ctx, config);
		};
</script>

templates/includes/navbar.html
{% load staticfiles %}
<nav class="navbar navbar-default navbar-fixed-top">
        <div>
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                        aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

            </div>

            <div class="pull-left" style="width: 250px;"><a class="navbar-brand" href="{% url 'accounts:dashboard' %}"><span class="ml10">VOIPX meeting manager</span></a></div>
            <div id="navbar" class="navbar-collapse collapse" aria-expanded="false" style="height: 1px;">


                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">

                        <a href="#" class="dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="true">
                            <img src="{% static 'img/user.png' %}"> {{ user }}
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                            <li><a href="{% url 'accounts:own_profile_details' %}">My Profile</a></li>
                            <li><a href="{% url 'accounts:own_password_change' %}">Change password</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                        </ul>
                    </li>
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </nav>

templates/includes/sidebar.html
<!-- Sidebar -->
<div id="sidebar-wrapper" style="overflow: auto">
    <ul class="sidebar-nav brand-clear">
        <li><a href="/" aria-hidden="true"></i> <i class="fa fa-home" aria-hidden="true"></i> Home </a></li>


        <br>
        <li class="sidebar-title" style="margin-top: 0;">Meeting Management</li>
        <li><a href="{% url 'room:room_list' %}"> <i class="fa fa-angle-double-right" aria-hidden="true"></i>Meetings</a></li>

        <br>
        {% if user.profile.user_type == 'admin' %}
        <li class="sidebar-title" style="margin-top: 0;">User Management</li>
        <li><a href="{% url 'restrictions:restriction_list' %}"> <i class="fa fa-angle-double-right" aria-hidden="true"></i>Manage Host Users</a></li>
        <li><a href="{% url 'accounts:create_creator' %}"> <i class="fa fa-angle-double-right" aria-hidden="true"></i>Create Host User</a></li>
        {% endif %}

        {% if user.is_staff %}
            <li class="sidebar-title" style="margin-top: 0;">Admin User Management</li>
            <li><a href="{% url 'accounts:admin_list' %}"> <i class="fa fa-angle-double-right" aria-hidden="true"></i>Mange admin</a></li>
        {% endif %}



    </ul>
</div>
<!-- /#sidebar-wrapper -->