accounts/urls.py
from django.urls import path
from accounts.views import *

app_name = 'accounts'
urlpatterns = [
    # path('register/', RegisterView.as_view(), name='register'),
    path('login/', login_view, name='login'),
    path('verify-otp/', VerifyOtpView.as_view(), name='verify-otp'),
    path('logout/', logout_view, name='logout'),
    path('login/submit/', login_submit, name='login_submit'),
    path('create/creator/', CreateUserView.as_view(), name="create_creator"),
    path('create/admin/', CreateAdminView.as_view(), name="create_admin"),
    path('admins/', AdminListView.as_view(), name="admin_list"),
    path('creator/<int:pk>/delete/', DeleteUserView.as_view(), name="delete_creator"),
    path('user/<int:pk>/update/', UpdateUserPassword.as_view(), name="update_user_password"),
    path('admins/<int:pk>/update/', AdminUpdateView.as_view(), name="admin_update"),
    path('', dashboard, name='dashboard'),
    path('calender/', calender_view, name='calendar'),
    path('directorySearch/', directorySearch, name='directorySearch'),
    path('profile/own/', own_profile_details,name='own_profile_details'),
    path('password-change/own/', own_password_change,name='own_password_change'),

]

jitsi_helper/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from qr_code import urls as qr_code_urls

urlpatterns = [
    # path('admin/', admin.site.urls),
    url(r'^qr_code/', include(qr_code_urls, namespace="qr_code")),
    url(r'^', include('accounts.urls')),
    url(r'^', include('room.urls')),
    url(r'^', include('restrictions.urls')),
]

room/urls.py
from django.urls import path
from room.views import *

app_name = 'room'
urlpatterns = [
    path('room/create/', RoomCreateView.as_view(), name='create_room'),
    path('room/', RoomListView.as_view(), name='room_list'),
    path('room/<int:pk>/join/', RoomJoinView.as_view(), name='join_room'),
    path('room/<int:pk>/delete/', RoomDeleteView.as_view(), name='delete_room'),
    path('room/<str:uid>/join/as-guest/', GuestJoinView.as_view(), name='join_guest_room'),
    path('room/update/<int:pk>/', RoomUpdateView.as_view(), name='room_update'),
    path('room/<int:pk>/details/json/', RoomJsonDetailsView.as_view(), name="room_json_details"),
    path('room/sync_google/json/', RoomSyncGoogle.as_view(), name="room_google_sync"),
    path('room/sync_outlook/json/', RoomSyncOutlook.as_view(), name="room_outlook_sync"),
    path('room/google_calender/not_synced/json/', RoomGoogleCalenderListView.as_view(), name="room_google_calender"),
    path('room/outlook_calender/not_synced/json/', RoomOutlookCalenderListView.as_view(), name="room_outlook_calender"),
]

accounts/models.py
import uuid

from django.contrib.auth.base_user import BaseUserManager
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.
class MyUserManager(BaseUserManager):
    def create_superuser(self, email, username, password=None):
        user = self.model(
            email=self.normalize_email(email),
            username=username
        )
        user.set_password(password)
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        profile = UserProfile.objects.create(
            user=user,
            user_uid=uuid.uuid4(),
            user_type=UserProfile.ADMIN,
            name=username
        )
        return user



class JitsiUser(AbstractUser):
    objects = MyUserManager()


class UserProfile(models.Model):
    CREATOR, ADMIN = 'creator', 'admin'
    USER_TYPE_CHOICES = ((CREATOR, "Content Creator"), (ADMIN, "Admin member"), )

    user = models.OneToOneField(JitsiUser, models.CASCADE, related_name='profile')
    user_uid = models.CharField(max_length=255, default='')
    name = models.CharField(max_length=255)
    user_type = models.CharField(choices=USER_TYPE_CHOICES, max_length=255)
    totp_key = models.CharField(max_length=20, null=True)

class VerificationCode(models.Model):
    user = models.ForeignKey(JitsiUser, on_delete=models.CASCADE)
    email = models.EmailField()
    code = models.CharField(max_length=50)
    is_verified = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    verified_at = models.DateTimeField(null=True)


    def __str__(self):
        return self.email

accounts/forms.py
import pyotp
from django import forms
from django.core.exceptions import NON_FIELD_ERRORS

from accounts.models import UserProfile, JitsiUser


class LoginForm(forms.Form):
    username = forms.CharField(max_length=200, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(max_length=200, widget=forms.PasswordInput(attrs={'class': 'form-control'}))


class UpdateAdminForm(forms.ModelForm):
    class Meta:
        model = JitsiUser
        fields = ['is_active', 'is_staff', 'is_superuser']



class OwnPasswordForm(forms.Form):
    old_password = forms.CharField(max_length=200, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password = forms.CharField(max_length=200, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    confirm_password = forms.CharField(max_length=200, widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    def __init__(self, user, *args, **kwargs):
        super(OwnPasswordForm, self).__init__(*args, **kwargs)
        self.user = user


    def clean(self):
        super().clean()
        clean_data = self.cleaned_data
        old_password = self.cleaned_data.get('old_password')
        if not old_password or not self.user.check_password(old_password):
            self.add_error('old_password', forms.ValidationError("Old password is not correct"))
        password = self.cleaned_data.get('password')
        confirm_password = self.cleaned_data.get('confirm_password')
        if password != confirm_password:
            self.add_error('password', forms.ValidationError("Password and confirm password should match"))

class OtpForm(forms.Form):
    otp = forms.CharField(max_length=200, widget=forms.TextInput(attrs={'class': 'form-control'}))


class UserPasswordForm(forms.Form):
    password = forms.CharField(max_length=200, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    confirm_password = forms.CharField(max_length=200, widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    def clean(self):
        super().clean()
        clean_data = self.cleaned_data
        password = self.cleaned_data.get('password')
        confirm_password = self.cleaned_data.get('confirm_password')
        if password != confirm_password:
            self.add_error('password', forms.ValidationError("Password and confirm password should match"))


class UserForm(forms.ModelForm):
    class Meta:
        model = JitsiUser
        fields = ['username', 'email', 'password', ]
        error_messages = {
            NON_FIELD_ERRORS: {
                'unique_together': "%(model_name)s's %(field_labels)s are not unique.",
            }
        }

        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.TextInput(attrs={'class': 'form-control'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control'})
        }


class UserProfileForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = [
            'name',
        ]

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
        }

accounts/views.py
import uuid
from random import randint

import pyotp
from django import views
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import User
from django.core.mail import EmailMultiAlternatives
from django.http import JsonResponse
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import ListView

from accounts.auth_helper import is_user_admin
from accounts.forms import LoginForm, UserForm, UserProfileForm, UpdateAdminForm, OtpForm, UserPasswordForm, \
    OwnPasswordForm
from accounts.models import UserProfile, JitsiUser, VerificationCode
from jitsi_helper.local import VIDEO_URL
from jitsi_helper.settings import EMAIL_HOST_USER
from restrictions.forms import RestrictionFormWithoutUserForm
from restrictions.models import Restrictions
from utils.helpers import get_obj, split_name


def login_view(request):
    form = LoginForm()
    return render(request, "login.html", {"form": form})

class EmailVerificationMixin(object):
    from_email = EMAIL_HOST_USER
    subject = 'Action required'
    default_host = VIDEO_URL

    @staticmethod
    def create_code(user):
        try:
            # verification_code = str(uuid.uuid4())
            verification_code = str(randint(100000, 999999))
            VerificationCode.objects.create(
                user=user,
                email=user.email,
                code=verification_code
            )
            return verification_code
        except Exception as e:
            print(e)
            return None

    def send_mail(self, content, mail_to):
        try:
            msg = EmailMultiAlternatives(self.subject, content, self.from_email, [mail_to])
            msg.attach_alternative(content, "text/html")
            msg.send()
            return True
        except Exception as e:
            return False

    def verify_code(self, user, code):
        return VerificationCode.objects.filter(
            user=user,
            code=code,
            email=user.email
        ).exists()

    def send_verification_email(self, user, verification_host=None):
        verification_code = self.create_code(user)
        html_content = 'Use this code to verify your email: %s <br> ' % verification_code
        html_content += '<br><p>This code is valid for 48 hours</p><br><br>'
        html_content += 'Thanks for staying with talk.gomeeting.org'
        self.send_mail(html_content, user.email)
        return True


class RegisterView(View):
    form = UserForm
    profile_form = UserProfileForm
    template = "register.html"

    def get(self, request, *args, **kwargs):
        form = self.form()
        profile_form = self.profile_form()
        return render(request, self.template, locals())

    def post(self, request, *args, **kwargs):
        form = self.form(request.POST)
        profile_form = self.profile_form(request.POST)
        if form.is_valid() and profile_form.is_valid():
            user = form.save(commit=False)
            user.password = make_password(form.cleaned_data.get('password'))
            user.first_name, user.last_name = split_name(profile_form.cleaned_data.get('name'))
            user.is_active = False
            user.save()

            user_profile = profile_form.save(commit=False)
            user_profile.user_uid = uuid.uuid4()
            user_profile.user = user
            user_profile.user_type = UserProfile.ADMIN
            user_profile.save()

            Restrictions.objects.create(
                user=user,
                max_member_count=-1,
                max_room_count=-1,
                max_time_length=-1
            )

            return redirect(reverse("accounts:login"))
        return render(request, self.template, locals())


@method_decorator(login_required, name='dispatch')
class CreateUserView(View):
    form = UserForm
    profile_form = UserProfileForm
    restriction_form = RestrictionFormWithoutUserForm
    template = 'create_creator.html'

    def get(self, request, *args, **kwargs):
        form = self.form()
        profile_form = self.profile_form()
        restriction_form = self.restriction_form()
        return render(request, self.template, locals())

    def post(self, request, *args, **kwargs):
        form = self.form(request.POST)
        profile_form = self.profile_form(request.POST)
        restriction_form = self.restriction_form(request.POST)
        if form.is_valid() and profile_form.is_valid() and restriction_form.is_valid():
            user = form.save(commit=False)
            user.password = make_password(form.cleaned_data.get('password'))
            user.first_name, user.last_name = split_name(profile_form.cleaned_data.get('name'))
            user.save()

            user_profile = profile_form.save(commit=False)
            user_profile.user_uid = uuid.uuid4()
            user_profile.user = user
            user_profile.user_type = UserProfile.CREATOR
            user_profile.save()

            restriction = restriction_form.save(commit=False)
            restriction.user = user
            restriction.save()

            return redirect(reverse("accounts:dashboard"))
        return render(request, self.template, locals())

@method_decorator(login_required, name='dispatch')
class DeleteUserView(View):
    def get(self, request, *args, **kwargs):
        if request.user.is_staff and request.user.profile.user_type == UserProfile.ADMIN and request.user.is_superuser:
            user_id = kwargs.get('pk')
            JitsiUser.objects.get(id=user_id).delete()
            return redirect(reverse("accounts:dashboard"))

class UpdateUserPassword(View):
    form = UserPasswordForm
    def get(self, request, *args, **kwargs):
        if request.user.is_staff and request.user.profile.user_type == UserProfile.ADMIN and request.user.is_superuser:
            user_id = kwargs.get('pk')
            update_user = JitsiUser.objects.get(id=user_id)
            form = self.form()
            return render(request, 'update_user_password.html', locals() )
    def post(self, request, *args, **kwargs):
        if request.user.is_staff and request.user.profile.user_type == UserProfile.ADMIN and request.user.is_superuser:
            form = self.form(request.POST)
            user_id = kwargs.get('pk')
            update_user = JitsiUser.objects.get(id=user_id)
            if form.is_valid():
                update_user.set_password(form.cleaned_data['password'])
                update_user.save()
                return redirect(reverse('accounts:dashboard'))
            return render(request, 'update_user_password.html', locals())

@method_decorator(login_required, name='dispatch')
class VerifyOtpView(View, EmailVerificationMixin):
    template='otp.html'
    form = OtpForm

    def get(self, request):
        self.send_verification_email(request.user)
        form = self.form()
        return render(request, self.template, locals())

    def post(self, request):
        form = self.form(data=request.POST)
        if form.is_valid():
            code = form.cleaned_data.get('otp')
            if self.verify_code(request.user, code):
                request.session['email_verified'] = True

                return redirect(reverse('accounts:dashboard'))
            form.add_error("otp", "Your otp is worng")
        return render(request, self.template, locals())



@method_decorator(login_required, name='dispatch')
class CreateAdminView(View):
    form = UserForm
    profile_form = UserProfileForm
    template = 'create_admin.html'

    def get(self, request, *args, **kwargs):
        form = self.form()
        profile_form = self.profile_form()
        return render(request, self.template, locals())

    def post(self, request, *args, **kwargs):
        form = self.form(request.POST)
        profile_form = self.profile_form(request.POST)
        if form.is_valid() and profile_form.is_valid():
            user = form.save(commit=False)
            user.password = make_password(form.cleaned_data.get('password'))
            user.first_name, user.last_name = split_name(profile_form.cleaned_data.get('name'))
            user.save()

            user_profile = profile_form.save(commit=False)
            user_profile.user_uid = uuid.uuid4()
            user_profile.user = user
            user_profile.user_type = UserProfile.ADMIN
            user_profile.save()

            Restrictions.objects.create(
                user=user,
                max_member_count=-1,
                max_room_count=-1,
                max_time_length=-1
            )

            return redirect(reverse("accounts:dashboard"))
        return render(request, self.template, locals())

@method_decorator(login_required, name='dispatch')
class AdminListView(ListView):
    model = UserProfile
    template_name = 'admin_list.html'

    def get_queryset(self):
        if self.request.user.is_superuser:
            return UserProfile.objects.filter(user_type=UserProfile.ADMIN)
        elif self.request.user.is_staff:
            return UserProfile.objects.filter(user_type=UserProfile.ADMIN, user__is_superuser=False)
        return UserProfile.objects.filter(user_type=UserProfile.ADMIN, user__is_superuser=False, user__is_staff=False)


@method_decorator(login_required, name='dispatch')
class AdminUpdateView(View):
    form = UpdateAdminForm
    template_name = 'update_admin.html'

    def get(self, request, *args, **kwargs):
        admin_id = kwargs.get('pk')
        admin_user = JitsiUser.objects.get(pk=admin_id, profile__user_type=UserProfile.ADMIN)
        form = self.form(instance=admin_user)
        return render(request, self.template_name, locals())

    def post(self, request, *args, **kwargs):

accounts/templates/admin_list.html
{% extends 'base.html' %}
{% block contents %}
    {% if user.is_staff %}
    <div>
    <h3 class="pull-left">Manage admins</h3>
        <div class="pull-right">
            {% if user.is_staff and user.is_superuser %}
                <a href="{% url 'accounts:create_admin' %}" class="btn btn-primary">Create an admin</a>
            {% endif %}
        </div>

    <div class="clearfix"></div>
    </div>
    <table class="table">
        <tr>
            <th>Name</th>
            <th>Username</th>
            <th>Email</th>
            <th>Active</th>
            <th>Staff</th>
            <th>Superuser</th>
            <th></th>
        </tr>
        {% for admin in object_list %}
            <tr>
                <td>{{ admin.user.first_name }}</td>
                <td>
                    {{ admin.user.username }}
                </td>
                <td>
                    {{ admin.user.email }}
                </td>
                <td>
                    {% if admin.user.is_active %}
                    Active
                    {% else %}
                        Inactive
                    {% endif %}
                </td>
                <td>
                    {% if admin.user.is_staff %}
                    Staff
                    {% else %}
                        -
                    {% endif %}
                </td>
                <td>
                    {% if admin.user.is_superuser %}
                    Super User
                    {% else %}
                        -
                    {% endif %}
                </td>

                <td>
                    <a href="{% url 'accounts:admin_update' admin.user.id %}" class="btn btn-primary">Update</a>
                    {% if user.is_staff and user.is_superuser %}
                        <a href="{% url 'accounts:update_user_password' admin.user.id %}" class="btn btn-primary">Update Password</a>
                        <a href="{% url 'accounts:delete_creator' admin.user.id %}" class="btn btn-danger">Delete user</a>
                    {% endif %}

                </td>
            </tr>
        {% endfor %}
    </table>
    {% else %}
        <div class="alert alert-danger">
            You do not have access to this page yet
        </div>
    {% endif %}
{% endblock %}

accounts/templates/calender.html
{% extends 'base.html' %}
{% block contents %}
    <div class="row">
        <div class="col-md-4">
            <button id="authorize_button" style="display: none;" onclick="signIn()">Authorize</button>
            <button id="add_event_button" style="display: none;" onclick="addEvent()">Add Event</button>
            <button id="signout_button" style="display: none;" onclick="signOut()">Sign Out</button>
            <pre id="content" style="white-space: pre-wrap;"></pre>
        </div>
    </div>
{% endblock %}
{% block page_script %}
    <script src="https://cdn.jsdelivr.net/npm/bluebird@3.7.2/js/browser/bluebird.min.js"></script>
    <script src="https://alcdn.msftauth.net/lib/1.2.1/js/msal.js"
            integrity="sha384-9TV1245fz+BaI+VvCjMYL0YDMElLBwNS84v3mY57pXNOt6xcUYch2QLImaTahcOP"
            crossorigin="anonymous"></script>

    <!-- Graph SDK -->
    <script src="https://cdn.jsdelivr.net/npm/@microsoft/microsoft-graph-client/lib/graph-js-sdk.js"></script>
    <script type="text/javascript">
        const msalConfig = {
            auth: {
                clientId: '5b005403-dd7b-4872-be03-435a9a9d43f3',
                redirectUri: 'http://localhost:8000/calender/'
            },
            cache: {
                cacheLocation: "sessionStorage",
                storeAuthStateInCookie: false,
                forceRefresh: false
            }
        };

        const loginRequest = {
            scopes: [
                'profile',
                'user.read',
                'calendars.readWrite'
            ]
        };
        const authorizeButton = document.getElementById('authorize_button');
        const addEventButton = document.getElementById('add_event_button');
        const signOutButton = document.getElementById('signout_button');
        const contentElement = document.getElementById('content');

        function showAccountNav(account, data) {

            if (account) {
                authorizeButton.style.display = 'none';
                signOutButton.style.display = 'inline';
                addEventButton.style.display = 'inline';
                contentElement.appendChild(document.createTextNode("account:" + JSON.stringify(account) + "\n"));
            } else {
                // Show a "sign in" button
                authorizeButton.style.display = 'inline';
                signOutButton.style.display = 'none';
                addEventButton.style.display = 'none'
            }
            contentElement.appendChild(document.createTextNode("data:" + JSON.stringify(data) + "\n"));
        }

        function showError(error) {
            var alert = createElement('div', 'alert alert-danger');

            var message = createElement('p', 'mb-3', error.message);
            alert.appendChild(message);

            if (error.debug) {
                var pre = createElement('pre', 'alert-pre border bg-light p-2');
                alert.appendChild(pre);

                var code = createElement('code', 'text-break text-wrap',
                    JSON.stringify(error.debug, null, 2));
                pre.appendChild(code);
            }

            mainContainer.innerHTML = '';
            mainContainer.appendChild(alert);
        }

        function updatePage(account, data) {
            showAccountNav(account, data);
        }

        async function signIn() {
            // Login
            try {
                await msalClient.loginPopup(loginRequest);
                console.log('id_token acquired at: ' + new Date().toString());
                if (msalClient.getAccount()) {
                    updatePage(msalClient.getAccount());
                    getEvents();
                }
            } catch (error) {
                console.log(error);

            }
        }

        function signOut() {
             msalClient.logout();
        }

        const msalClient = new Msal.UserAgentApplication(msalConfig);
        const options =
            new MicrosoftGraph.MSALAuthenticationProviderOptions([
                'user.read',
                'calendars.read'
            ]);
        // Create an authentication provider for the implicit flow
        const authProvider =
            new MicrosoftGraph.ImplicitMSALAuthenticationProvider(msalClient, options);
        // Initialize the Graph client
        const graphClient = MicrosoftGraph.Client.initWithMiddleware({authProvider});

        async function getEvents() {
            try {
                let events = await graphClient
                    .api('/me/events')
                    .select('subject,organizer,start,end')
                    .orderby('createdDateTime DESC')
                    .get();

                updatePage(msalClient.getAccount(), events);
            } catch (error) {
                updatePage(msalClient.getAccount(), {
                    message: 'Error getting events',
                    debug: error
                });
            }
        }

        if (msalClient.getAccount() && !msalClient.isCallback(window.location.hash)) {
            updatePage(msalClient.getAccount());
            getEvents();
        }
        updatePage();

        async function addEvent() {
            var time_zone = Intl.DateTimeFormat().resolvedOptions().timeZone;
            const event = {
                subject: "Let's go for lunch",
                body: {
                    contentType: "HTML",
                    content: "Does mid month work for you?"
                },
                start: {
                    dateTime: "2019-03-15T12:00:00",
                    timeZone: time_zone
                },
                end: {
                    dateTime: "2019-03-15T14:00:00",
                    timeZone: time_zone
                },
                location: {
                    displayName: "http://a.com"
                },
                attendees: []
            };
            let res = await graphClient.api('/me/calendar/events').post(event);
            updatePage(msalClient.getAccount(), res);
        }
    </script>
{% endblock %}

accounts/templates/create_admin.html
{% extends 'base.html' %}
{% load static %}
{% block contents %}
        {% if user.profile.user_type == 'admin' and user.is_staff and user.is_superuser %}
        <div class="">
            <h1>Create admin</h1>
        </div>
        {% if errors %}
            <div class="alert alert-danger">{{ errors }}</div>
        {% endif %}
        <div>
            {% if form.errors %}
                <div class="alert alert-danger">
                    {{ form.errors }}
                </div>
            {% endif %}
            <form action="." method="post">
                {% csrf_token %}
                {% for field in form.visible_fields %}
                    <div class="form-group">
                        {% if field.field.widget.is_hidden is not True %}
                            {% if field.field.required %}
                                <label>{{ field.label }}<span class="required"> * </span></label>
                            {% else %}
                                <label>{{ field.label }}</label>
                            {% endif %}
                        {% endif %}
                        {{ field }}
                    </div>
                {% endfor %}

                {% for field in profile_form.visible_fields %}
                    <div class="form-group">
                        {% if field.field.widget.is_hidden is not True %}
                            {% if field.field.required %}
                                <label>{{ field.label }}<span class="required"> * </span></label>
                            {% else %}
                                <label>{{ field.label }}</label>
                            {% endif %}
                        {% endif %}
                        {{ field }}
                    </div>
                {% endfor %}
                {% for field in restriction_form.visible_fields %}
                    <div class="form-group">
                        {% if field.field.widget.is_hidden is not True %}
                            {% if field.field.required %}
                                <label>{{ field.label }}<span class="required"> * </span></label>
                            {% else %}
                                <label>{{ field.label }}</label>
                            {% endif %}
                        {% endif %}
                        {{ field }}
                        {% if field.help_text %}
                            <small class="form-text text-muted">{{ field.help_text }}</small>
                        {% endif %}
                    </div>
                {% endfor %}
                <button type="submit" class="btn btn-primary">Create</button>

            </form>
        </div>
    {% else %}
    <div class="alert alert-danger">
    You do not have access to this page yet
    </div>
    {% endif %}
{% endblock %}

accounts/templates/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% block contents %}
{% endblock %}

accounts/templates/login.html
{% extends "layout.html" %}
{% load staticfiles %}

{% block contents %}
    <div class="container">
        <div class="text-center">
            <img src="{% static 'img/company_logo.jpeg' %}" width="250">
        </div> <br> <br>
        {% if errors %}
            <div class="alert alert-danger margin-center" style="width: 400px;">{{ errors }}</div>
        {% endif %}
        <div class="card shadow panel p30 margin-center" style="width: 400px;">
            <form action="{% url 'accounts:login_submit' %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label>Username/Email</label>
                    {{ form.username }}
                </div>
                <div class="form-group">
                    <label>Password</label>
                    {{ form.password }}
                </div>

                <div class="clearfix">
                    <div class="pull-right">
                        <button type="submit" class="btn btn-default">Login</button>
                    </div>
                </div>
            </form>
        </div>

    </div>
{% endblock %}

accounts/templates/otp.html
{% extends "layout.html" %}
{% load staticfiles %}
{% load qr_code %}

{% block contents %}
    <div class="container">
        <div class="text-center">
            <img src="{% static 'img/company_logo.jpeg' %}" width="250">
        </div> <br> <br>
        {% if form.errors %}
            <div class="alert alert-danger margin-center" style="width: 400px;">{{ form.errors }}</div>
        {% endif %}
        <div class="card shadow panel p30 margin-center" style="width: 400px;">

            <div>
                Check your email and please give otp
            </div>
            <form action="." method="post">
                {% csrf_token %}
                <div class="form-group">
                    {{ form.otp }}
                </div>

                <div class="clearfix">
                    <div class="pull-right">
                        <button type="submit" class="btn btn-default">Verify OTP</button>
                    </div>
                </div>
            </form>
        </div>

    </div>
{% endblock %}

accounts/templates/own_profile.html
{% extends 'base.html' %}
{% block contents %}

    <div class="row">
        <div class="col-md-12">
            <br>
            <h3>{{ profile.name }}</h3>
            <p>
                {{ profile.user_type | upper }}
            </p>
            <p>
                Username: <strong>{{ profile.user.username }}</strong>
            </p>
            <p>
                Email address: <strong>{{ profile.user.email }}</strong>
            </p>
            <p>
                Last logged in: <strong>{{ profile.user.last_login }}</strong>
            </p>
        </div>
    </div>
{% endblock %}